language: python
install: pip install tox-travis
script: tox
stages:
  - name: test
jobs:
  include:
    - stage: test
      python: 3.6
    - stage: test
      python: 3.7
    - stage: test
      python: 3.8
