PREFIX frbroo: <https://cidoc-crm.org/frbroo/sites/default/files/FRBR2.4-draft.rdfs#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX crm: <http://www.cidoc-crm.org/cidoc-crm/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
SELECT ?person ?occupation ?time ?employer ?name ?graph ?type ?typeLabel ?appellation  ?occ WHERE {
  GRAPH ?graph {
    BIND(<{{id}}> as ?person)
    ?person crm:P1_is_identified_by ?appellation.
  ?appellation rdf:type crm:E33_E41_Linguistic_Appellation;
    rdf:value ?name.
    OPTIONAL {
    ?appellation crm:P2_has_type ?type.
      
  FILTER(?type NOT IN(<https://sk.acdh.oeaw.ac.at/types/person/persname/male>, <https://sk.acdh.oeaw.ac.at/types/person/persname/female>)
        )
    }
    
    OPTIONAL{?person crm:P14i_performed ?occ.
    ?occ rdf:type frbroo:F51_Pursuit;
      rdfs:label ?occupation.
    OPTIONAL { ?occ crm:P10_falls_within ?employer. }
    OPTIONAL { ?occ (crm:P4_has_time-span/rdfs:label) ?time. }
             }
  }
        OPTIONAL{?type rdfs:label ?typeLabel}
}