{ ?subject (rdfs:label|skos:prefLabel) ?label. }
  UNION
  {
    ?subject crm:P1_is_identified_by ?appellation.
    ?appellation rdf:type crm:E33_E41_Linguistic_Appellation;
      rdfs:label ?label.
  }
  ?subject rdf:type ?type.
  FILTER(?type IN({% for type in subject_types %}{{type.value}}{% if not loop.last %}, {% endif %}{% endfor %}))
  ?label bds:search "{{q}}*"^^xsd:string;
    bds:minRelevance "0.5";
    bds:relevance ?score;
    bds:matchAllTerms "true".